# Generated by Django 5.0.2 on 2025-06-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsn_social_network", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="shares_count",
            field=models.IntegerField(default=0),
        ),
    ]
