# Generated by Django 5.0.2 on 2025-07-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsn_social_network", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("public", "Öffentlich"),
                    ("friends", "Freunde"),
                    ("private", "Privat"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
