# Generated by Django 5.0.2 on 2025-06-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsn_social_network', '0002_post_shares_count'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE bsn_social_network_post ADD COLUMN shares_count INTEGER DEFAULT 0 NOT NULL;",
            reverse_sql="ALTER TABLE bsn_social_network_post DROP COLUMN shares_count;"
        ),
    ]
