# Generated by Django 5.0.2 on 2025-06-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsn_social_network", "0003_auto_20250622_2123"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="media_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("document", "Document"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
