# Generated by Django 5.0.2 on 2025-07-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsn_social_network', '0004_groupevent_groupeventrsvp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='required_token_contract',
            field=models.CharField(blank=True, help_text='Contract-Adresse des erforderlichen Tokens (optional)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='token_gated',
            field=models.BooleanField(default=False, help_text='Ist die Gruppe token-gated?'),
        ),
    ]
