# Generated by Django 5.0.2 on 2025-07-17 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsn_social_network', '0005_group_required_token_contract_group_token_gated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('options', models.JSONField(default=list)),
                ('votes', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='bsn_social_network.post')),
            ],
        ),
    ]
