# Generated by Django 5.0.2 on 2025-06-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsn_social_network", "0006_blockeduser_followrelationship_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="miningprogress",
            name="is_mining",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="miningprogress",
            name="last_activity_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="miningprogress",
            name="last_heartbeat",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="miningprogress",
            name="last_inactive_check",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
