# Generated by Django 5.0.2 on 2025-06-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsn_social_network", "0007_miningprogress_is_mining_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(
                blank=True, help_text="URL to user's profile picture", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="cover_url",
            field=models.URLField(
                blank=True, help_text="URL to user's cover/banner image", null=True
            ),
        ),
    ]
