# Generated by Django 5.0.2 on 2025-06-23 13:49

import bsn_social_network.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsn_social_network", "0008_user_avatar_url_user_cover_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokentransaction",
            name="transaction_hash",
            field=models.CharField(
                default=bsn_social_network.models.generate_transaction_hash,
                max_length=64,
                unique=True,
            ),
        ),
    ]
