# Generated by Django 5.0.2 on 2025-06-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsn_social_network", "0010_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="caption",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="story_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video"), ("text", "Text")],
                default="image",
                max_length=20,
            ),
        ),
    ]
