# Generated by Django 5.0.2 on 2025-06-26 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsn_social_network", "0012_storyview"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boost_type",
                    models.CharField(
                        choices=[
                            ("post", "Post Creation"),
                            ("comment", "Comment Creation"),
                            ("like", "Like Given"),
                            ("share", "Content Share"),
                            ("login", "Daily Login"),
                            ("referral", "Referral Success"),
                        ],
                        max_length=20,
                    ),
                ),
                ("multiplier", models.DecimalField(decimal_places=2, max_digits=5)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boosts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "boost",
                "ordering": ["-created_at"],
            },
        ),
    ]
