import Index from './Index';
export default Index;

export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as ResetPassword } from './ResetPassword';
export { default as Dashboard } from './Dashboard';
export { default as Feed } from './Feed';
export { default as Profile } from './Profile';
export { default as Wallet } from './Wallet';
export { default as NotFound } from './NotFound';
export { default as Mining } from './Mining';
export { default as NFTMarketplace } from './NFTMarketplace';
export { default as CreateToken } from './CreateToken';
export { default as NFTCollection } from './NFTCollection';
export { default as NFTDetails } from './NFTDetails';
export { default as CreateNFT } from './CreateNFT';
export { default as CreateNFTCollection } from './CreateNFTCollection';
export { default as MessagesPage } from './MessagesPage';
export { default as Notifications } from './Notifications';
export { default as NotificationSettings } from './NotificationSettings';
export { default as SearchPage } from './SearchPage';
export { default as FriendsPage } from './FriendsPage';
export { default as GroupsOverviewPage } from './GroupsOverviewPage';
export { default as AlbumDetail } from './AlbumDetail';
